defmodule GlutenFreeGuide.Repo.Migrations.ScaffoldNoo14Domain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :display_name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:recipes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :summary, :text
      add :privacy, :text, null: false, default: "private"
      add :servings, :bigint
      add :duration_minutes, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "recipes_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:recipe_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :instruction, :text, null: false
      add :timer_seconds, :bigint

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_steps_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:recipe_steps, [:recipe_id, :position],
             name: "recipe_steps_unique_step_position_per_recipe_index"
           )

    create table(:recipe_ingredients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal
      add :unit, :text
      add :preparation_note, :text

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_ingredients_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :ingredient_id, :uuid, null: false
    end

    create unique_index(:recipe_ingredients, [:recipe_id, :ingredient_id, :preparation_note],
             name: "recipe_ingredients_unique_ingredient_per_recipe_index"
           )

    create table(:progress_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :metadata, :map, null: false, default: %{}

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "progress_events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :course_track_id, :uuid, null: false
      add :lesson_id, :uuid
    end

    create table(:lessons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :title, :text, null: false
      add :body, :text, null: false
      add :position, :bigint, null: false
      add :course_track_id, :uuid, null: false
    end

    create unique_index(:lessons, [:course_track_id, :position],
             name: "lessons_unique_lesson_position_per_course_index"
           )

    create unique_index(:lessons, [:course_track_id, :slug],
             name: "lessons_unique_lesson_slug_per_course_index"
           )

    create table(:ingredients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:recipe_ingredients) do
      modify :ingredient_id,
             references(:ingredients,
               column: :id,
               name: "recipe_ingredients_ingredient_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ingredients) do
      add :name, :text, null: false
      add :gluten_status, :text, null: false, default: "unknown"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ingredients, [:name], name: "ingredients_unique_ingredient_name_index")

    create table(:dietary_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :allergens, {:array, :text}, null: false, default: []
      add :altitude_ft, :bigint
      add :experience_level, :text, null: false, default: "beginner"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "dietary_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:dietary_profiles, [:user_id],
             name: "dietary_profiles_unique_user_profile_index"
           )

    create table(:course_tracks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:progress_events) do
      modify :course_track_id,
             references(:course_tracks,
               column: :id,
               name: "progress_events_course_track_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :lesson_id,
             references(:lessons,
               column: :id,
               name: "progress_events_lesson_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:lessons) do
      modify :course_track_id,
             references(:course_tracks,
               column: :id,
               name: "lessons_course_track_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:course_tracks) do
      add :slug, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
    end

    create unique_index(:course_tracks, [:slug], name: "course_tracks_unique_course_slug_index")
  end

  def down do
    drop_if_exists unique_index(:course_tracks, [:slug],
                     name: "course_tracks_unique_course_slug_index"
                   )

    alter table(:course_tracks) do
      remove :status
      remove :description
      remove :title
      remove :slug
    end

    drop constraint(:lessons, "lessons_course_track_id_fkey")

    alter table(:lessons) do
      modify :course_track_id, :uuid
    end

    drop constraint(:progress_events, "progress_events_course_track_id_fkey")

    drop constraint(:progress_events, "progress_events_lesson_id_fkey")

    alter table(:progress_events) do
      modify :lesson_id, :uuid
      modify :course_track_id, :uuid
    end

    drop table(:course_tracks)

    drop constraint(:dietary_profiles, "dietary_profiles_user_id_fkey")

    drop_if_exists unique_index(:dietary_profiles, [:user_id],
                     name: "dietary_profiles_unique_user_profile_index"
                   )

    drop table(:dietary_profiles)

    drop_if_exists unique_index(:ingredients, [:name],
                     name: "ingredients_unique_ingredient_name_index"
                   )

    alter table(:ingredients) do
      remove :updated_at
      remove :inserted_at
      remove :gluten_status
      remove :name
    end

    drop constraint(:recipe_ingredients, "recipe_ingredients_ingredient_id_fkey")

    alter table(:recipe_ingredients) do
      modify :ingredient_id, :uuid
    end

    drop table(:ingredients)

    drop_if_exists unique_index(:lessons, [:course_track_id, :slug],
                     name: "lessons_unique_lesson_slug_per_course_index"
                   )

    drop_if_exists unique_index(:lessons, [:course_track_id, :position],
                     name: "lessons_unique_lesson_position_per_course_index"
                   )

    drop table(:lessons)

    drop constraint(:progress_events, "progress_events_user_id_fkey")

    drop table(:progress_events)

    drop constraint(:recipe_ingredients, "recipe_ingredients_recipe_id_fkey")

    drop_if_exists unique_index(
                     :recipe_ingredients,
                     [:recipe_id, :ingredient_id, :preparation_note],
                     name: "recipe_ingredients_unique_ingredient_per_recipe_index"
                   )

    drop table(:recipe_ingredients)

    drop constraint(:recipe_steps, "recipe_steps_recipe_id_fkey")

    drop_if_exists unique_index(:recipe_steps, [:recipe_id, :position],
                     name: "recipe_steps_unique_step_position_per_recipe_index"
                   )

    drop table(:recipe_steps)

    drop constraint(:recipes, "recipes_owner_user_id_fkey")

    drop table(:recipes)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
